a300_0000:
  clearpath_diagnostic_updater:
    ros__parameters:
      serial_number: 'a300-0000'
      platform_model: 'a300'
      ros_distro: 'jazzy'
      latest_apt_firmware_version: 'simulated'
      installed_apt_firmware_version: 'simulated'
      use_sim_time: True
      bms_state_rate: 2.5
      bms_state_tolerance: 0.2
      mcu_protocol: 'uros'
